/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoListRouteImport } from './routes/todo-list'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as LenRouteImport } from './routes/len'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as IndexRouteImport } from './routes/index'

const TodoListRoute = TodoListRouteImport.update({
  id: '/todo-list',
  path: '/todo-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LenRoute = LenRouteImport.update({
  id: '/len',
  path: '/len',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/len': typeof LenRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/todo-list': typeof TodoListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/len': typeof LenRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/todo-list': typeof TodoListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/len': typeof LenRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/todo-list': typeof TodoListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/counter' | '/len' | '/sign-in' | '/sign-up' | '/todo-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counter' | '/len' | '/sign-in' | '/sign-up' | '/todo-list'
  id:
    | '__root__'
    | '/'
    | '/counter'
    | '/len'
    | '/sign-in'
    | '/sign-up'
    | '/todo-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounterRoute: typeof CounterRoute
  LenRoute: typeof LenRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TodoListRoute: typeof TodoListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo-list': {
      id: '/todo-list'
      path: '/todo-list'
      fullPath: '/todo-list'
      preLoaderRoute: typeof TodoListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/len': {
      id: '/len'
      path: '/len'
      fullPath: '/len'
      preLoaderRoute: typeof LenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounterRoute: CounterRoute,
  LenRoute: LenRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TodoListRoute: TodoListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
