/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowcaseTodoListRouteImport } from './routes/showcase.todo-list'
import { Route as ShowcaseLenRouteImport } from './routes/showcase.len'
import { Route as ShowcaseCounterRouteImport } from './routes/showcase.counter'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseTodoListRoute = ShowcaseTodoListRouteImport.update({
  id: '/showcase/todo-list',
  path: '/showcase/todo-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseLenRoute = ShowcaseLenRouteImport.update({
  id: '/showcase/len',
  path: '/showcase/len',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseCounterRoute = ShowcaseCounterRouteImport.update({
  id: '/showcase/counter',
  path: '/showcase/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/showcase/counter': typeof ShowcaseCounterRoute
  '/showcase/len': typeof ShowcaseLenRoute
  '/showcase/todo-list': typeof ShowcaseTodoListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/showcase/counter': typeof ShowcaseCounterRoute
  '/showcase/len': typeof ShowcaseLenRoute
  '/showcase/todo-list': typeof ShowcaseTodoListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/showcase/counter': typeof ShowcaseCounterRoute
  '/showcase/len': typeof ShowcaseLenRoute
  '/showcase/todo-list': typeof ShowcaseTodoListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/showcase/counter'
    | '/showcase/len'
    | '/showcase/todo-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/showcase/counter'
    | '/showcase/len'
    | '/showcase/todo-list'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/showcase/counter'
    | '/showcase/len'
    | '/showcase/todo-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ShowcaseCounterRoute: typeof ShowcaseCounterRoute
  ShowcaseLenRoute: typeof ShowcaseLenRoute
  ShowcaseTodoListRoute: typeof ShowcaseTodoListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/todo-list': {
      id: '/showcase/todo-list'
      path: '/showcase/todo-list'
      fullPath: '/showcase/todo-list'
      preLoaderRoute: typeof ShowcaseTodoListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/len': {
      id: '/showcase/len'
      path: '/showcase/len'
      fullPath: '/showcase/len'
      preLoaderRoute: typeof ShowcaseLenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/counter': {
      id: '/showcase/counter'
      path: '/showcase/counter'
      fullPath: '/showcase/counter'
      preLoaderRoute: typeof ShowcaseCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ShowcaseCounterRoute: ShowcaseCounterRoute,
  ShowcaseLenRoute: ShowcaseLenRoute,
  ShowcaseTodoListRoute: ShowcaseTodoListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
